# Generated by Django 5.2.4 on 2025-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('wishlist', 'Wishlist')], max_length=10)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
